[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/tietie-backend",
]
exclude = [
    "projects/tietie-frontend",
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
